"""
Define and solve cut generation problems.
"""

from cutgeneratingfunctionology.igp import *
from .execptions import *
from .cut_score import cutScore
from .scipy_cgp_interface import *
from .cgf_specializations import * # imports cut generating functionololgy and specalizations
from scipy.optimize import minimize as scipy_minimize
from cvxpy import Variable as cvxpy_Variable, Maximize as cvxpy_Maximize, Minimize as cvxpy_Minimize, Problem as cvxpy_Problem
import logging
import time


cut_generation_problem_logger = logging.getLogger(__name__)
cut_generation_problem_logger.setLevel(logging.ERROR)

# minimal_exprction_cashe_logging = True

#avail_rep_elems = minimal_exprction_cache_info()["avail_rep_elems"]


# Helper functions/model enforcement

def find_f_index(min_pwl):
    r"""
    Assume a model function, pi_p, with a finite number of breakpoints is given.
    Finds the index i such that pi_p(lambda_i) = 1.

    INPUT:
    - igp piecewise linear function

    OUTPUT:
    - integer
    """
    return min_pwl.end_points().index(find_f(min_pwl))


def sparse_enough_breakpoints(bkpt_old, epsilon):
    r"""
    Considers the space PWL(*<=n) and finds a point breakpoint sequence bkpt
    such that  ||bkpt_old - bkpt||_infty < epsilon and that  bkpt[i+1]-bkpt[i] > epsilon xor bkpt[i] = bkpt[i+1].
    This implies that d((bkpt_old,f), (bktp,f))< espilon and bkpt is "sparse enough".

    Picking epsilon to be a "correct value" models a maximum number of breakpoints in algorithms "bkpt_as_param" and "value_poly_lp".  

    INPUT:
    - breakpoint sequence

    OUTPUT:
    - breakpoint sequence such that bkpt[i+1]-bkpt[i] > epsilon xor bkpt[i] = bkpt[i+1].

    TESTS::
    >>> from parametricCutGen.cut_generation_problem import *
    >>> sparse_enough_breakpoints([0, 10**-7, 4/5], 10**-6)
    [0, 4/5]
    """
    bkpt = list(tuple(bkpt_old)) # cheap way of deep copying lists
    for i in range(len(bkpt)-1):
        if abs(bkpt[i]) < epsilon:
            bkpt[i] = 0
        # 1 equiv 0 mod 1
        elif abs(bkpt[i] - 1) < epsilon:
            bkpt[i] = 0
        elif abs(bkpt[i] - bkpt[i+1]) < epsilon:
            bkpt[i+1] = bkpt[i]
    if abs(bkpt[len(bkpt)-1] -1) < epsilon or abs(bkpt[len(bkpt)-1])< epsilon:
        bkpt[len(bkpt)-1] = 0
    return bkpt

def inf_norm_of_cont_pwl(f, g):
    return max([abs(v) for v in (f-g).values_at_end_points()])

def log_problem_result(bkpt, val, binvarow, binvc, f):
    cut_generation_problem_logger.info(f"Cut generation problem solved.")
    cut_generation_problem_logger.info(f"breakpoitns: {bkpt}")
    cut_generation_problem_logger.info(f"values: {val}")
    cut_generation_problem_logger.info(f"row: {binvarow}")
    cut_generation_problem_logger.info(f"objective:{binvc}")
    cut_generation_problem_logger.info(f"f: {f}")

class cgpTimer:
    def __init__(self, max_time):
        if max_time is None:
            max_time = 2**63-1
        self._max_time = max_time
        self._start_time = time.process_time()

    def solver_time_out(self):
        if time.process_time() - self._start_time >= self._max_time:
            cut_generation_problem_logger.warning(f"Solver timed out.")
            return True
        return False

# cutGenProblemParametersNames = ["algorithm", "cut_score", "max_num_bkpt", "multithread", "prove_seperator", "epsilon", "M", "max_cgp_solver_time", "max_cgf_solver_iter"]

class cutGenerationProblem:
    r"""
    A class for solving a cut generation problem (cgp).
    
    The cut generation problem is defined as max cutScore(cut) s.t. cut in CutPool.
    
    cutSpace is defined by the algorithm chosen.
    
    \"full\" correspond to the full space of cuts generated from PiMin<=max_num_of_bkpts.
    
    \"bkpt\_as\_param\" correspond the space of cuts generated by assuming breakpoints are parameters
    and the cuts are generated from the value polyhedron of the breakpoints.
    
    \"value_poly_lp" specialization of \"bkpt\_as\_param\" to linear functions. Using an LP solver rather
    than a generic non linear solver and is in the ambient space of value parameters.
    
    The problem assumes that all minimal functions belong to a family (epsilon, M) charts.

    The cgp optional keywords are listed below.

    :algorithm: - str(full), str(bkpt_as_param), str(value_poly_lp)
    :backend: - None or str(pplite)
    :cut_store: - valid argument for initializing :class:`cutScore`
    :epsilon: - Chart epsilon value, real number > 0. 
    :M: -  Chart lipschitz constant, real number > 0.
    :max_cgp_solver_time: - Optimal real clock time limit for solving problem. Takes positive values.
    :max_num_of_bkpts: - integer >= 2, maximum number of breakpoints a minimal function is allowed to have.
    :multithread: - bool, Not implemented, intended for "full" algorithm.
    :prove_seperator: - bool, proves every function used is actually a function that can be used to generate a separator.
    :rel_tol: - real number >=0, stopping condition for solving cgp. If the distance between two solutions of the cgp is less than `rel_tol` then they are considered equal and the solver will halt and return the most recent solution.
    :show_proof: - bool, Outputs proof from `cutgeneratingfunctionology`.
    
    TESTS::
    >>> from parametricCutGen.cut_generation_problem import *

    """
    # *, makes arguments keyword only. Order shouldn't matter in terms of inputs. The problem will write it's own parameters into a cgp_params dict.
    def __init__(self, *, algorithm=None, backend=None, cut_score=None,  epsilon=1e-6, M = 1e6, max_cgp_solver_time=None, max_num_of_bkpts=4, multithread=False, objective_sense="maximize", prove_seperator=False, show_proof=False, cvxpy_solve_args=None, cvxpy_solve_kwds=None, scipy_args=None, scipy_kwds=None):
        """
        TESTS::
        >>> from parametricCutGen.cut_generation_problem import *
        >>> cgp_full = cutGenerationProblem(algorithm="full", backend="pplite", cut_score="steepest_direction", max_num_of_bkpts=4)
        >>> cgp_full_params_test = cgp_full.get_cgp_input_parameters()
        >>> cgp_full_test = cutGenerationProblem(**cgp_full_params_test)
        >>> cgp_full_test is cgp_full
        False
        """
        self._cgp_input_parameters = {**locals()} # copy input parameters; only inital inputs here.
        self._cgp_input_parameters.pop("self") # This is required to ensure that when parameters are reused for initlaziation, problems doens't arise.
        # TODO: Implement a way so that cgps with the same parameter are the same object; maybe.
        self._objective_sense = objective_sense
        if self._objective_sense not in ["maximize", "minimize"]:
            raise ValueError("Objective senese should be either maximize or minimize.")
        if algorithm is None or algorithm.lower() == "full":
            self._algorithm = "full"
#            if max_num_of_bkpts not in avail_rep_elems:
#                cut_generation_problem_logger.warning(f"Function cache {max_num_of_bkpts} is not available; generation of functions at runtime is not advised.")
        elif algorithm.lower() == "bkpt_as_param":
            self._algorithm = "bkpt_as_param"
        elif algorithm.lower() == "value_poly_lp":
            self._algorithm = "value_poly_lp"
        else:
            raise ValueError("No other algorithms are supported at this time.")
        self._cut_score_generator = scipyCutScoreForBkptAsParam(cut_score, epsilon, M)
        self._prove_seperator = prove_seperator
        self._show_proof = show_proof
        self._backend = backend
        self._epsilon= epsilon
        self._M = M
        self._max_cgp_solver_time = max_cgp_solver_time
        self._max_num_of_bkpts = max_num_of_bkpts
        self._cvxpy_args = cvxpy_solve_args
        self._cvxpy_kwds = cvxpy_solve_kwds
        self._scipy_kewords = scipy_kwds
        self._scipy_args = scipy_args

        
    def __repr__(self):
        return f"Cut generation problem using algorithm {self._algorithm}."

    def solve(self, binvrow, binvarow, f, costs, cols=None, rows=None, scip=None):
        r"""Solves the parameterized problem.

        Interprets the options and calls the correct solving algorithm.

        Passes any instructions to the underlying solver.
        """
        if self._algorithm == "full":
            cgf, cut_score = self._algorithm_full_space(binvrow, binvarow, f, costs, cols, rows, scip)
        elif self._algorithm == "bkpt_as_param":
            cgf, cut_score = self._algorithm_bkpt_as_param(binvrow, binvarow, f, costs, cols, rows, scip)
        elif self._algorithm == "value_poly_lp":
            cgf, cut_score = self._algorithm_value_poly_lp(binvrow, binvarow, f, costs, cols, rows, scip)
        return cgf, cut_score

    def _algorithm_full_space(self, binvrow, binvarow, f, costs, cols=None, rows=None, scip=None):
        r"""
        Solves the problem given a row of B^-1A and the reduced costs
        """
        raise NotImplementedError("Full space algorithm is under development.")

    def _algorithm_bkpt_as_param(self, binvrow, binvarow, f, costs, cols=None, rows=None, scip=None):
        """
        Solves the problem given a row of B^-1A and the reduced costs
        """
        frac_f = fractional(QQ(f))
        symmetrized_bkpts = [0, frac_f]
        # symmertized breakpoints should all be in [0,1)
        for b in binvarow:
            sage_b = fractional(QQ(b))
            b_sym = frac_f - sage_b
            if b_sym > 0:
                symmetrized_bkpts += [sage_b, b_sym]
            elif b_sym < 0:
                symmetrized_bkpts += [sage_b, 1+b_sym]
        symmetrized_bkpts = unique_list(symmetrized_bkpts)
        symmetrized_bkpts.sort()
        # it might be worth while to ensure if we have sufficient difference between breakpoints.
        model_sparsity = max(float(1/self._max_num_of_bkpts), self._epsilon)
        sparse_bkpt = unique_list(sparse_enough_breakpoints(symmetrized_bkpts, model_sparsity))
        if frac_f not in sparse_bkpt:
            sparse_bkpt = [x for x in sparse_bkpt if abs(frac_f -x) > self._epsilon]
            sparse_bkpt.append(frac_f)
        num_bkpt = len(sparse_bkpt)
        # ensure a breakpoint sequence is given
        sparse_bkpt.sort()
        sparse_bkpt = [QQ(bi) for bi in sparse_bkpt]    
        f_index = sparse_bkpt.index(frac_f)
        cut_generation_problem_logger.debug(f"sparse_bkpt={sparse_bkpt}\nf_index={f_index}")    
        # to use scipy; we find an inital point via a polyhedron
        n = len(sparse_bkpt)
        #cut_generation_problem_logger.debug(f"gen poly")
        if self._backend == 'pplite':
            Value_Poly = pplite_NNC_Polyhedron(dim_type = n, spec_elem = "universe", topology = "nnc")
            bsa = BasicSemialgebraicSet_polyhedral_pplite_NNC_Polyhedron(n, Value_Poly)
        else:
            Value_Poly = NNC_Polyhedron(n)
            bsa = BasicSemialgebraicSet_polyhedral_ppl_NNC_Polyhedron(n, Value_Poly)
        value_cons = value_nnc_polyhedron_constraints(sparse_bkpt, f_index, backend=self._backend)
        for con in value_cons:
            try:
                #cut_generation_problem_logger.debug(f"{con, type(con)}")
                Value_Poly.add_constraint(con)
            except Exception as e:
                continue
        #cut_generation_problem_logger.debug(f"find point")
        x0 = [float(x_i) for x_i in bsa.find_point()]
        scipy_cons = map_polyhedral_bsa_to_scipy_LinearConstraint(bsa, self._epsilon)
        #cut_generation_problem_logger.debug(f"solve")
        if scip is not None:
            cutcoefs_expr, cutrhs_expr, integral_indices, lp_soln = self.getParamaterizedCutExpr(scip, cols, rows, binvrow, binvarow, f, sparse_bkpt, f_index)
            s = self._cut_score_generator.gen_cut_score(f_index,  cutcoefs_expr, cutrhs_expr, lp_soln, costs, integral_indices)
            if self._objective_sense == "maximize":
                def cut_score(value_parameters):
                    return -1* s(value_parameters)
            else:
                 def cut_score(value_parameters):
                    return s(value_parameters)
        else:
            raise NotImplementedError
        result = scipy_minimize(cut_score, x0, constraints=scipy_cons)
        #cut_generation_problem_logger.debug(f"fin")
        score = result.fun
        values = to_sage_rationals(result.x)
        b = sparse_bkpt
        v = values
        pi_p = piecewise_function_from_breakpoints_and_values(b+[1], v+[0])
        log_problem_result(b, v, binvarow, costs, f)
        if self._prove_seperator:
            res = minimality_test(pi_p, self._show_proof) # add someway to log certificates.
            cut_generation_problem_logger.info(f"Minimality of cgf: {res}")
        return pi_p, score

    def _algorithm_value_poly_lp(self, binvrow, binvarow, f, costs, cols=None, rows=None, scip=None):
        problem_timer = cgpTimer(self._max_cgp_solver_time)
        frac_f = fractional(QQ(f))
        symmetrized_bkpts = [0, frac_f]
        # symmertized breakpoints should all be in [0,1)
        for b in binvarow:
            sage_b = fractional(QQ(b))
            b_sym = frac_f - sage_b
            if b_sym > 0:
                symmetrized_bkpts += [sage_b, b_sym]
            elif b_sym < 0:
                symmetrized_bkpts += [sage_b, 1+b_sym]
        symmetrized_bkpts = unique_list(symmetrized_bkpts)
        symmetrized_bkpts.sort()
        # it might be worth while to ensure if we have sufficient difference between breakpoints.
        model_sparsity = max(float(1/self._max_num_of_bkpts), self._epsilon)
        sparse_bkpt = unique_list(sparse_enough_breakpoints(symmetrized_bkpts, model_sparsity))
        if frac_f not in sparse_bkpt:
            sparse_bkpt = [x for x in sparse_bkpt if abs(frac_f -x) > self._epsilon]
            sparse_bkpt.append(frac_f)
        num_bkpt = len(sparse_bkpt)
        # Ensure a breakpoint sequence is given.
        sparse_bkpt.sort()
        # Data bkpt sequences need to be sage types.
        sparse_bkpt = to_sage_rationals(sparse_bkpt)
        f_index = sparse_bkpt.index(frac_f)
        # lets use cvxpy to solve the problem directly
        cvxpy_vals = cvxpy_Variable(len(sparse_bkpt)) # aka the values
        value_cons = value_nnc_polyhedron_constraints(sparse_bkpt, f_index, cvxpy_vals, coeff_type='float', epsilon=self._epsilon)
        
        map_sage_expr_to_cvpxy_expr = lambda expr : sum( float(expr.coefficient(expr.parent().gens_dict()['gamma'+str(i)]))*cvxpy_vals[i] + float(expr.constant_coefficient()) for i in range(num_bkpt) )
        # data from scip is being passed in
        if scip is not None:
            cutcoefs_expr, cutrhs_expr, integral_indices, lp_soln = self.getParamaterizedCutExpr(scip, cols, rows, binvrow, binvarow, f, sparse_bkpt, f_index)
            cut_generation_problem_logger.debug(f"sage:{cutcoefs_expr, cutrhs_expr}")
            # if the rhs gets used in teh furture; make sure to include the constant terms.
            steepest_dir_expr = sum( map_sage_expr_to_cvpxy_expr(cutcoefs_expr[i])*costs[i] for i in range(len(costs)) )
        else: # assume pure IP; testing and verifcation purposes.
            cut_generation_problem_logger.warning("pure IP problem is assumed.") #TODO: more useful warning.
            pi = pwl_with_value_parameters_and_bkpts_fixed(sparse_bkpt, f_index)
            steepest_dir_expr = sum( map_sage_expr_to_cvpxy_expr(pi(binvarow[i]))*costs[i] for i in range(len(costs)) )
        if self._objective_sense == "maximize":
            obj = cvxpy_Maximize(steepest_dir_expr)
        else:
            obj = cvxpy_Minimize(steepest_dir_expr)
        prob = cvxpy_Problem(obj, value_cons)
        if self._cvxpy_args is None and self._cvxpy_kwds is None:
            prob.solve()
        elif self._cvxpy_args is None and self._cvxpy_kwds is not None:
            prob.solve(**self._cvxpy_kwds)
        elif self._cvxpy_args is not None and self._cvxpy_kwds is not None:
            prob.solve(*self._cvxpy_args, **self._cvxpy_kwds)
        else:
            prob.solve(*self._cvxpy_args)
        score = prob.value
        values = to_sage_rationals(cvxpy_vals.value)
        b = sparse_bkpt
        v = values
        pi_p = piecewise_function_from_breakpoints_and_values(b+[1], v+[0])
        log_problem_result(b, v, binvarow, costs, f)
        if self._prove_seperator: # note; in general the minimality test will be false unless using an exact rational solver for the lp problem.
            res = minimality_test(pi_p, self._show_proof) # add someway to log certificates.
            cut_generation_problem_logger.info(f"Minimality of cgf: {res}")
        return pi_p, score

    def getParamaterizedCutExpr(self, scip, cols, rows, binvrow, binvarow, primsol, bkpt, f_index):
        """ Given the row (binvarow, binvrow) of the tableau, computes and expression for the cut in the value parameters (gammai).

        :param primsol:  is the rhs of the tableau row
        :param cols:     are the variables
        :param rows:     are the slack variables
        :param binvrow:  components of the tableau row associated to the basis inverse
        :param binvarow: components of the tableau row associated to the basis inverse * A
        :param vals:    value parameters
    
        The intersection cut is given by
         sum(pi_p(a_j) x_j, j in J_I) \geq 1
        where J_I are the integer non-basic variables and J_C are the continuous.
        f_0 is the fractional part of primsol
        a_j is the j-th coefficient of the row and f_j its fractional part
        Note: we create -% <= -f_0 !!
        Note: this formula is valid for a problem of the form Ax = b, x>= 0. Since we do not have
        such problem structure in general, we have to (implicitly) transform whatever we are given
        to that form. Specifically, non-basic variables at their lower bound are shifted so that the lower
        bound is 0 and non-basic at their upper bound are complemented.
        """
        coord_names = ['gamma'+str(i) for i in range(len(bkpt))]
        K = PolynomialRing(QQ, names=coord_names, order='lex')
        # initialize
        cutcoefs_expr = [K.zero()] * len(cols)
        cutrhs_expr = K.zero()
        integral_indices = []
        lp_soln = []
        pi_p = pwl_with_value_parameters_and_bkpts_fixed(bkpt, f_index, poly_ring=K)
        f = K(fractional(QQ(primsol)))
        def psi(x):
            if x < 0:
                slope = pi_p.functions()[-1]._slope
                neg_part = FastLinearFunction(slope, K.zero())
                return neg_part(x)
            else:
                return pi_p.functions()[0](x)
        # rhs of the cut is the fractional part of the LP solution for the basic variable
        cutrhs_expr = -f
        # Generate cut coefficients for the original variables
        for c in range(len(cols)):
            col = cols[c]
            var = col.getVar()
            lp_soln.append(var.getLPSol())
            if var.vtype() != "CONTINUOUS":
                integral_indices.append(c)
            assert col is not None
            status = col.getBasisStatus()

            # Get simplex tableau coefficient
            if status == "lower":
                # Take coefficient if nonbasic at lower bound
                rowelem = binvarow[c]
            elif status == "upper":
                # Flip coefficient if nonbasic at upper bound: x --> u - x
                rowelem = -binvarow[c]
            else:
                # variable is nonbasic free at zero -> cut coefficient is zero, skip OR
                # variable is basic, skip
                assert status == "zero" or status == "basic"
                continue

            # Integer variables
            if col.isIntegral():
                cutelem_expr = fractional(QQ(rowelem))
                cutelem_expr = -1*f*pi_p(cutelem_expr)
            else:
                # Continuous variables
                cutelem_expr = -1*f*psi(QQ(rowelem))

            # cut is define when variables are in [0, infty). Translate to general bounds
            if not cutelem_expr is 0: # could be 0 polynomial
                if col.getBasisStatus() == "upper":
                    cutelem_expr = -cutelem_expr
                    cutrhs_expr += cutelem_expr * col.getUb()
                else:
                    cutrhs_expr += cutelem_expr * col.getLb()
                # Add coefficient to cut in dense form
                cutcoefs_expr[col.getLPPos()] = cutelem_expr

        # Generate cut coefficients for the slack variables; skip basic ones
        for c in range(len(rows)):
            row = rows[c]
            assert row != None
            status = row.getBasisStatus()

            # free slack variable shouldn't appear
            assert status != "zero"

            # Get simplex tableau coefficient
            if status == "lower":
                # Take coefficient if nonbasic at lower bound
                rowelem = binvrow[row.getLPPos()]
                # But if this is a >= or ranged constraint at the lower bound, we have to flip the row element
                if not scip.isInfinity(-row.getLhs()):
                    rowelem = -rowelem
            elif status == "upper":
                # Take element if nonbasic at upper bound - see notes at beginning of file: only nonpositive slack variables
                # can be nonbasic at upper, therefore they should be flipped twice and we can take the element directly.
                rowelem = binvrow[row.getLPPos()]
            else:
                assert status == "basic"
                continue

            # if row is integral we can strengthen the cut coefficient
            if row.isIntegral() and not row.isModifiable():
                cutelem_expr = fractional(QQ(rowelem))
                cutelem_expr = -1*f*pi_p(cutelem_expr)
            else:
                # Continuous variables
                cutelem_expr = -1*f*psi(QQ(rowelem))

            # cut is define in original variables, so we replace slack by its definition
            if cutelem_expr is 0: # sage type; 
                # get lhs/rhs
                rlhs = row.getLhs()
                rrhs = row.getRhs()
                assert scip.isLE(rlhs, rrhs)
                assert not scip.isInfinity(rlhs) or not scip.isInfinity(rrhs)

                # If the slack variable is fixed, we can ignore this cut coefficient
                if scip.isFeasZero(rrhs - rlhs):
                  continue

                # Unflip slack variable and adjust rhs if necessary: row at lower means the slack variable is at its upper bound.
                # Since SCIP adds +1 slacks, this can only happen when constraints have a finite lhs
                if row.getBasisStatus() == "lower":
                    assert not scip.isInfinity(-rlhs)
                    cutelem_expr = -cutelem_expr

                rowcols = row.getCols()
                rowvals = row.getVals()

                assert len(rowcols) == len(rowvals)

                # Eliminate slack variable: rowcols is sorted: [columns in LP, columns not in LP]
                for i in range(row.getNLPNonz()):
                    cutcoefs_expr[rowcols[i].getLPPos()] -= cutelem_expr * rowvals[i]

                act = scip.getRowLPActivity(row)
                rhsslack = rrhs - act
                if scip.isFeasZero(rhsslack):
                    assert row.getBasisStatus() == "upper" # cutelem != 0 and row active at upper bound -> slack at lower, row at upper
                    cutrhs_expr -= cutelem_expr * (rrhs - row.getConstant())
                else:
                    assert scip.isFeasZero(act - rlhs)
                    cutrhs_expr -= cutelem_expr * (rlhs - row.getConstant())
        cut_generation_problem_logger.debug(f"{lp_soln}")
        
        return cutcoefs_expr, cutrhs_expr, integral_indices, lp_soln
        # apply algebraic maps to produce cuts in terms of val; val is non-> return list
#        n = len(bkpt)
#        coord_names = ['gamma'+str(i) for i in range(n)]
#        map_to_vector = lambda expr : [expr.coefficient(expr.parent().gens_dict()[name]) for name in coord_names]
#        list_of_vecs_in_gamma_params = [ map_to_vector(expr) for expr in cutcoefs_expr ]
#        cutrhs_expr [ sum( vec[i]*val[i] for i in range(n)) for vec in list_of_vecs_in_gamma_params ]
#

    def _algorithm_custom(self, binvarow, binvc, f):
        # For future use.
        raise NotImplementedError

    
    def get_cgp_input_parameters(self):
        """
        Returns a dictionary parameters used to initalize the cut generation problem.
        """
        return self._cgp_input_parameters
        
    
