"""
Define and solve cut generation problems.
"""

from cutgeneratingfunctionology.igp import *
from minimalFunctionCache.utils import minimal_function_cache_info
# the rational conversion QQ is imported from cutgeneratingfunctionology.
from .execptions import *
from .cut_score import cutScore
from .generic_solvers import scipyCutGenProbelmSolverInterface, cvxpyCutGenProblemSolverInterface
import logging
import time

cut_generation_problem_logger = logging.getLogger(__name__)
cut_generation_problem_logger.setLevel(logging.DEBUG)

# minimal_function_cashe_logging = True

avail_rep_elems = minimal_function_cache_info()["avail_rep_elems"]


def find_f_index(min_pwl):
    r"""
    Assume a model function, pi_p, with a finite number of breakpoints is given.
    Finds the index i such that pi_p(lambda_i) = 1.

    INPUT:
    - igp piecewise linear function

    OUTPUT:
    - integer
    """
    return min_pwl.end_points().index(find_f(min_pwl))


def sparse_enough_breakpoints(bkpt_old, epsilon):
    r"""
    Considers the space PWL(*<=n) and finds a point breakpoint sequence bkpt
    such that  ||bkpt_old - bkpt||_infty < epsilon and that  bkpt[i+1]-bkpt[i] > epsilon xor bkpt[i] = bkpt[i+1].
    This implies that d((bkpt_old,f), (bktp,f))< espilon and bkpt is "sparse enough".

    Picking epsilon to be a "correct value" models a maximum number of breakpoints in algorithms "bkpt_as_param" and "value_poly_lp".  

    INPUT:
    - breakpoint sequence

    OUTPUT:
    - breakpoint sequence such that bkpt[i+1]-bkpt[i] > epsilon xor bkpt[i] = bkpt[i+1].

    TESTS::
    >>> from parametricCutGen.cut_generation_problem import *
    >>> sparse_enough_breakpoints([0, 10**-7, 4/5], 10**-6)
    [0, 4/5]
    """
    bkpt = list(tuple(bkpt_old)) # cheap way of deep copying lists
    for i in range(len(bkpt)-1):
        if abs(bkpt[i]) < epsilon:
            bkpt[i] = 0
        # 1 equiv 0 mod 1
        elif abs(bkpt[i] - 1) < epsilon:
            bkpt[i] = 0
        elif abs(bkpt[i] - bkpt[i+1]) < epsilon:
            bkpt[i+1] = bkpt[i]
    if abs(bkpt[len(bkpt)-1] -1) < epsilon or abs(bkpt[len(bkpt)-1])< epsilon:
        bkpt[len(bkpt)-1] = 0
    return bkpt


def log_problem_result(bkpt, val, binvarow, binvc, f):
    cut_generation_problem_logger.info(f"Cut generation problem solved.")
    cut_generation_problem_logger.info(f"breakpoitns: {bkpt}")
    cut_generation_problem_logger.info(f"values: {val}")
    cut_generation_problem_logger.info(f"row: {binvarow}")
    cut_generation_problem_logger.info(f"objective:{binvc}")
    cut_generation_problem_logger.info(f"f: {f}")

class cgpTimer:
    def __init__(self, max_time):
        if max_time is None:
            max_time = 2**63-1
        self._max_time = max_time
        self._start_time = time.process_time()

    def solver_time_out(self):
        if time.process_time() - self._start_time >= self._max_time:
            cut_generation_problem_logger.warning(f"Solver timed out.")
            return True
        return False

# cutGenProblemParametersNames = ["algorithm", "cut_score", "max_num_bkpt", "multithread", "prove_seperator", "epsilon", "M", "max_cgp_solver_time", "max_cgf_solver_iter"]

class cutGenerationProblem:
    r"""
    A class for solving a cut generation problem (cgp).
    
    The cut generation problem is defined as max cutScore(cut) s.t. cut in CutPool.
    
    cutSpace is defined by the algorithm chosen.
    
    \"full\" correspond to the full space of cuts generated from PiMin<=max_num_of_bkpts.
    
    \"bkpt\_as\_param\" correspond the space of cuts generated by assuming breakpoints are parameters
    and the cuts are generated from the value polyhedron of the breakpoints.
    
    \"value_poly_lp" specialization of \"bkpt\_as\_param\" to linear functions. Using an LP solver rather
    than a generic non linear solver and is in the ambient space of value parameters.
    
    The problem assumes that all minimal functions belong to a family (epsilon, M) charts.

    The cgp optional keywords are listed below.

    :algorithm: - str(full), str(bkpt_as_param), str(value_poly_lp)
    :backend: - None or str(pplite)
    :cut_store: - valid argument for initializing :class:`cutScore`
    :epsilon: - Chart epsilon value, real number > 0. 
    :M: -  Chart lipschitz constant, real number > 0.
    :max_cgp_solver_time: - Optimal real clock time limit for solving problem. Takes positive values.
    :max_num_of_bkpts: - integer >= 2, maximum number of breakpoints a minimal function is allowed to have.
    :multithread: - bool, Not implemented, intended for "full" algorithm.
    :prove_seperator: - bool, proves every function used is actually a function that can be used to generate a separator.
    :rel_tol: - real number >0, stopping condition for solving cgp. If the distance between two solutions of the cgp is less than `rel_tol` then they are considered equal and the solver will halt and return the most recent solution.
    :show_proof: - bool, Outputs proof from `cutgeneratingfunctionology`.
    
    TESTS::
    >>> from parametricCutGen.cut_generation_problem import *
    >>> import logging
    >>> logging.disable()
    >>> gmic_equiv = cutGenerationProblem(algorithm="full", backend="pplite", cut_score="steepest_direction", max_num_of_bkpts=2)
    >>> cgp_full_4 = cutGenerationProblem(algorithm="full", backend="pplite", cut_score="steepest_direction", max_num_of_bkpts=4)
    >>> cgp_bkpt_as_param = cutGenerationProblem(algorithm="bkpt_as_param", backend="pplite", cut_score="steepest_direction", max_num_of_bkpts=100)
    >>> cgp_value_poly_lp = cutGenerationProblem(algorithm="value_poly_lp", backend="pplite", cut_score="steepest_direction", max_num_of_bkpts=100)
    >>> binvarow = [3.2, 4.1, 5.6, .2]
    >>> binvc = [1.2, 4.4, 5.6, -.1]
    >>> f = 1.8 # aka b of the row
    >>> sol_is_gmic = gmic_equiv.solve(binvarow, binvc, f)
    >>> cgp_full_4_sol = cgp_full_4.solve(binvarow, binvc, f)
    >>> cgp_bkpt_as_param_sol = cgp_bkpt_as_param.solve(binvarow, binvc, f)
    >>> cpg_value_poly_sol = cgp_value_poly_lp.solve(binvarow, binvc, f) # ||h-g||_infty ~ 0.015. g and h should have a similar solution since the problems are equivlant; impmentation choices make a difference!
    >>> cut_score_for_gmic_equiv =  sum(binvc[i]*sol_is_gmic(fractional(binvarow[i])) for i in range(4)); cut_score_for_gmic_equiv
    5.02500000000000
    >>> cut_score_for_cgp_full_4_sol = sum(binvc[i]*cgp_full_4_sol(fractional(binvarow[i])) for i in range(4)); cut_score_for_cgp_full_4_sol # the solution is GMIC
    5.02500000000000
    >>> cut_score_for_cgp_bkpt_as_param = sum(binvc[i]*cgp_bkpt_as_param_sol(fractional(binvarow[i])) for i in range(4)); cut_score_for_cgp_bkpt_as_param # Using additonal breakpoints can improve the result.
    5.69166666666666
    >>> cut_score_for_cgp_value_poly_lp = sum(binvc[i]*cpg_value_poly_sol(fractional(binvarow[i])) for i in range(4)); cut_score_for_cgp_value_poly_lp
    5.63837460764390
    >>> cut_score_for_gmic = sum(binvc[i]*sol_is_gmic(fractional(binvarow[i])) for i in range(4)); cut_score_for_gmic
    5.02500000000000
    >>> cgp_full_4_min = cutGenerationProblem(algorithm="full", backend="pplite", cut_score="steepest_direction", max_num_of_bkpts=4, objective_sense="minimize")
    >>> cpg_full_4_min_sol = cgp_full_4_min.solve(binvarow, binvc, f)
    >>> cut_score_for_cgp_full_4_min = sum(binvc[i]*cpg_full_4_min_sol(fractional(binvarow[i])) for i in range(4)); cut_score_for_cgp_full_4_min
    4.64166666666666
    """
    # *, makes arguments keyword only. Order shouldn't matter in terms of inputs. The problem will write it's own parameters into a cgp_params dict.
    def __init__(self, *, algorithm=None, backend=None, cut_score=None,  epsilon=None, M = None, max_cgp_solver_time=None, max_num_of_bkpts=4, multithread=False, objective_sense="maximize", prove_seperator=False, rel_tol=None, show_proof=False):
        """
        TESTS::
        >>> from parametricCutGen.cut_generation_problem import *
        >>> cgp_full = cutGenerationProblem(algorithm="full", backend="pplite", cut_score="steepest_direction", max_num_of_bkpts=4)
        >>> cgp_full_params_test = cgp_full.get_cgp_input_parameters()
        >>> cgp_full_test = cutGenerationProblem(**cgp_full_params_test)
        >>> cgp_full_test is cgp_full
        False
        """
        self._cgp_input_parameters = {**locals()} # copy input parameters; only inital inputs here.
        self._cgp_input_parameters.pop("self") # This is required to ensure that when parameters are reused for initlaziation, problems doens't arise.
        # TODO: Implement a way so that cgps with the same parameter are the same object; maybe.
        self._objective_sense = objective_sense
        if self._objective_sense not in ["maximize", "minimize"]:
            raise ValueError("Objective senese should be either maximize or minimize.")
        if algorithm is None or algorithm.lower() == "full":
            self._algorithm = "full"
            if max_num_of_bkpts not in avail_rep_elems:
                cut_generation_problem_logger.warning(f"Function cache {max_num_of_bkpts} is not available; generation of functions at runtime is not advised.")
            self._solver = scipyCutGenProbelmSolverInterface
        elif algorithm.lower() == "bkpt_as_param":
            self._algorithm = "bkpt_as_param"
            self._solver = scipyCutGenProbelmSolverInterface
        elif algorithm.lower() == "value_poly_lp":
            self._algorithm = "value_poly_lp"
            self._solver = cvxpyCutGenProblemSolverInterface
        else:
            raise ValueError("No other algorithms are supported at this time.")
        if cut_score is None:
            self._cut_score = cutScore(cut_score="steepest_direction", objective_sense=self._objective_sense)
        else:
            try:
                self._cut_score = cutScore(cut_score=cut_score,  objective_sense=self._objective_sense)
            except NameError:
                raise ValueError("Please provided a valid defined cutScore.")
        self._cut_score.set_sage_to_solver_type(self._solver.sage_to_solver_type)
        self._cut_space = None
        self._prove_seperator = prove_seperator
        self._show_proof = show_proof
        self._backend = backend
        if epsilon is not None:
            self._espilon = epsilon
        else:
            self._espilon = 10**-6
        if M is not None:
            self._M = M
        else:
            self._M = 10**6
        if rel_tol is not None:
            self._rel_tol = rel_tol
        else:
            self._rel_tol = 10**-6
        self._cut_score.set_rel_tol(self._rel_tol)
        self._cut_score.set_espilon(self._espilon)
        self._cut_score.set_lipschitz_constant(self._M)
        self._max_cgp_solver_time = max_cgp_solver_time
        self._max_num_of_bkpts = max_num_of_bkpts

        
    def __repr__(self):
        return f"Cut generation problem using algorithm {self._algorithm}."

    def solve(self, binvarow, binvc, f):
        r"""Solves the parameterized problem.

        Interprets the options and calls the correct solving algorithm.

        Passes any instructions to the underlying solver.
        """
        # assume MIP is a scip model; really we should be passing in and LP relaxation with variable information here.
        # The cut generation problem
        if self._algorithm == "full":
            cgf = self._algorithm_full_space(binvarow, binvc, f)
        elif self._algorithm == "bkpt_as_param":
            cgf = self._algorithm_bkpt_as_param(binvarow, binvc, f)
        elif self._algorithm == "value_poly_lp":
            cgf = self._algorithm_value_poly_lp(binvarow, binvc, f)
        return cgf

    def _algorithm_full_space(self, binvarow, binvc, f):
        r"""
        Solves the problem given a row of B^-1A and the reduced costs
        """
        self._cut_score.set_MIP_row(binvarow)
        self._cut_score.set_MIP_obj(binvc)
        self._cut_score.set_f_trust(f)
        frac_f = fractional(QQ(f))
        def cut_score(params):
            return self._cut_score(params)
        if self._objective_sense == "maximize": # cgp written as max cut_score(cut) st. cut \in cutSpace
            self._cut_score.set_objective_sense("minimize") # solvers are by default in the of min f(x) s.t. x\in S =  max -f(x) s.t. x\in S 
            best_result = -1*np.inf                         # f(x) = -1*cut_score(point) with objective sense min. 
        elif self._objective_sense == "minimize":           # f(x) = cut_score(point) with objective sense max.
            self._cut_score.set_objective_sense("maximize")
            best_result = np.inf
        best_point = None
        if self._cut_space is None: # load the semi algebraic cell descriptions of pi min.
             self._cut_space = PiMinContContainer(self._max_num_of_bkpts, backend=self._backend)
        # start the clock when the actual portion of the solving processes starts.
        problem_timer = cgpTimer(self._max_cgp_solver_time)
        self._cut_score.set_timer(problem_timer)
        for b, v in self._cut_space.get_rep_elems():
            # f is a bkpt when pi has a finite number of bkpts.
            # start by finding a bkpt sequence in the same cell
            # such that lambda_f_index = f holds.
            # pi(f) = 1;
            pi_test = piecewise_function_from_breakpoints_and_values(b+[1], v+[0])
            bsa_f_index = find_f_index(pi_test)
            self._cut_score.set_f_index(bsa_f_index)
            bkpt_bsa = nnc_poly_from_bkpt_sequence(b, backend=self._backend)
            lambda_f_index = bkpt_bsa.polynomial_map()[0].parent().gens()[bsa_f_index]
            bkpt_bsa.add_polynomial_constraint(lambda_f_index - frac_f, operator.eq)
            try:
                if not bkpt_bsa.upstairs().is_empty():
                    cut_generation_problem_logger.debug(f"Non empty bsa found.")
                    b0 = list(bkpt_bsa.find_point())
                    v0 = list(value_nnc_polyhedron_value_cords(b0, bsa_f_index).find_point())
                    # A feasible solution for cell problem has been found.
                    point = b0+v0
                    self._cut_score.set_feasible_point(point)
                    subdomain_with_f_constraint = bsa_of_rep_element(b0, v0)
                    lambda_f_index = subdomain_with_f_constraint.polynomial_map()[0].parent().gens()[bsa_f_index]
                    lhs =  lambda_f_index - frac_f
                    subdomain_with_f_constraint.add_polynomial_constraint(lhs, operator.eq)
                    self._cut_score.set_current_cell(subdomain_with_f_constraint)
                    subdomain_solver_constraints = self._solver.write_nonlinear_constraints_from_bsa(subdomain_with_f_constraint)
                    # Call a NL solver, attempt to solve the cell optimization problem.
                    try:
                        continue_solving = True
                        self._solver.nonlinear_solve(cut_score, point, subdomain_solver_constraints)
                    except ModelViolation: # _cut_score.get_feasible_point() for last feasible point.
                        cut_generation_problem_logger.debug(f"Cell {subdomain_with_f_constraint} solved with exit {ModelViolation}")
                    except SolverTimeOut:
                        continue_solving = False
                        cut_generation_problem_logger.error(f"Cell {subdomain_with_f_constraint} not solved fully with exit {SolverTimeOut}")
                    except SolverRelTolReached:
                        cut_generation_problem_logger.debug(f"Cell {subdomain_with_f_constraint} solved with exit {SolverRelTolReached}")
                    # Get the most recent feasible point and value according to cutScore
                    point = self._cut_score.get_feasible_point()  # this should always be defined.
                    result = self._cut_score.get_prev_result() # this should always be defined.
                    self._cut_score.set_prev_result(None)
                    self._cut_score.set_feasible_point(None)
                    cut_generation_problem_logger.debug(f"Cell {subdomain_with_f_constraint} result:{result}, best_result:{best_result}")
                    if self._objective_sense == "maximize": # multiply resutl by -1 to get objective value in original problem phrasing.
                        if best_result < -1*result:
                            best_result = -1*result
                            best_point = point
                    elif self._objective_sense == "minimize":  # f(x) = cut_score(point) with objective sense max.
                        if best_result > result:
                            best_result = result
                            best_point = point
                    if not continue_solving:
                        break
            except EmptyBSA:
                cut_generation_problem_logger.debug(f"BSA EMPTY.")
                continue
        # If best_result is +/- np.inf, the solver has failed to find any meaningful result.
        # The statement below should always be false.
        if best_result == np.inf or best_result == -1*np.inf:
            cut_generation_problem_logger.error(f"The solver has failed.  best_result is unbouded {best_result}")
            raise SolverError("The solver has failed.  best_result is unbouded {best_result}")
        sol_vals = [QQ(gamma_i) for gamma_i in best_point[self._max_num_of_bkpts:]]
        sol_bkpts = [QQ(lambda_i) for lambda_i in best_point[:self._max_num_of_bkpts]]
        pi_p = piecewise_function_from_breakpoints_and_values(sol_bkpts+[1],sol_vals+[0])
        log_problem_result(sol_bkpts, sol_vals, binvarow, binvc, f)
        if self._prove_seperator:
            res = minimality_test(pi_p) # add someway to log certificates.
            if not res:
                cut_generation_problem_logger.error(f"minimality of  {pi_p}: {res}")
        return pi_p

    def _algorithm_bkpt_as_param(self, binvarow, binvc, f):
        """
        Solves the problem given a row of B^-1A and the reduced costs
        """
        self._cut_score.set_MIP_row(binvarow)
        self._cut_score.set_MIP_obj(binvc)
        self._cut_score.set_f_trust(f)
        problem_timer = cgpTimer(self._max_cgp_solver_time)
        self._cut_score.set_timer(problem_timer)
        frac_f = fractional(QQ(f))
        def cut_score(params):
            return self._cut_score(params)
        if self._objective_sense == "maximize":             # scipy solver is in the form of min f(x) s.t. x\in S =  max -f(x) s.t. x\in S.
            self._cut_score.set_objective_sense("minimize") # f(x) = -1*cut_score(point) with objective sense min.
        elif self._objective_sense == "minimize":           # f(x) = cut_score(point) with objective sense max.
            self._cut_score.set_objective_sense("maximize")
        symmetrized_bkpts = [0, frac_f]
        # symmertized breakpoints should all be in [0,1)
        for b in binvarow:
            sage_b = fractional(QQ(b))
            b_sym = frac_f - sage_b
            if b_sym > 0:
                symmetrized_bkpts += [sage_b, b_sym]
            elif b_sym < 0:
                symmetrized_bkpts += [sage_b, 1+b_sym]
        symmetrized_bkpts = unique_list(symmetrized_bkpts)
        symmetrized_bkpts.sort()
        # it might be worth while to ensure if we have sufficient difference between breakpoints.
        model_sparsity = max(float(1/self._max_num_of_bkpts), self._espilon)
        sparse_bkpt = unique_list(sparse_enough_breakpoints(symmetrized_bkpts, model_sparsity))
        if frac_f not in sparse_bkpt:
            sparse_bkpt.append(frac_f)
        num_bkpt = len(sparse_bkpt)
        if num_bkpt == 2:
            cut_generation_problem_logger.debug("Parsed row data suggests to use GMIC.")
            cut_generation_problem_logger.debug("Dim of value polyhedron: 0")
            pi_p =  gmic(frac_f)
            log_problem_result(sparse_bkpt, [0, 1], binvarow, binvc, f)
            if self._prove_seperator:
                # we always have a separator here.
                cut_generation_problem_logger.debug(f"The minimality of the found cgf is {True}")
            # return gmic, the feasible set for the optimization problem is a single point which corresponds to gmic.
            return pi_p
        # ensure a breakpoint sequence is given
        sparse_bkpt.sort()
        f_index = sparse_bkpt.index(frac_f)
        self._cut_score.set_f_index(f_index)
        value_polyhedron = value_nnc_polyhedron(sparse_bkpt, f_index, backend=self._backend)
        cut_generation_problem_logger.debug(f"Dim of value polyhedron :{value_polyhedron.upstairs().ambient_dim()}")
        point = list(value_polyhedron.find_point())
        # initialize a feasible point for the cut scoring function to remember.
        self._cut_score.set_feasible_point(point)
        self._cut_score.set_current_cell(value_polyhedron)
        value_polyhedron_constraints = self._solver.write_linear_constraints_from_bsa(value_polyhedron)
        try:
            self._solver.nonlinear_solve(cut_score, point, value_polyhedron_constraints)
        except ModelViolation:
            cut_generation_problem_logger.debug(f"Value Poly {value_polyhedron} solved with exit {ModelViolation}")
        except SolverRelTolReached:
            cut_generation_problem_logger.debug(f"Value Poly {value_polyhedron} solved with exit {SolverRelTolReached}")
        except SolverTimeOut:
            cut_generation_problem_logger.error(f"Value Poly {value_polyhedron} not solved fully with exit {SolverTimeOut}")
        self._cut_score.set_timer(None)
        result_point = self._cut_score.get_feasible_point()
        val_result = [QQ(gamma_i) for gamma_i in result_point[num_bkpt:]]
        bkpt_result = [QQ(lambda_i) for lambda_i in result_point[:num_bkpt]]
        pi_p = piecewise_function_from_breakpoints_and_values(bkpt_result+[1], val_result+[0])
        log_problem_result(bkpt_result, val_result, binvarow, binvc, f)
        if self._prove_seperator:
            res = minimality_test(pi_p, self._show_proof) # add someway to log certificates.
            cut_generation_problem_logger.info(f"Minimality of cgf: {res}")
        return pi_p

    def _algorithm_value_poly_lp(self, binvarow, binvc, f):
        self._cut_score.set_MIP_row(binvarow)
        self._cut_score.set_MIP_obj(binvc)
        self._cut_score.set_f_trust(f)
        problem_timer = cgpTimer(self._max_cgp_solver_time)
        self._cut_score.set_timer(problem_timer)
        frac_f = fractional(QQ(f))
        symmetrized_bkpts = [0, frac_f]
        # symmertized breakpoints should all be in [0,1)
        for b in binvarow:
            sage_b = fractional(QQ(b))
            b_sym = frac_f - sage_b
            if b_sym > 0:
                symmetrized_bkpts += [sage_b, b_sym]
            elif b_sym < 0:
                symmetrized_bkpts += [sage_b, 1+b_sym]
        symmetrized_bkpts = unique_list(symmetrized_bkpts)
        symmetrized_bkpts.sort()
        # it might be worth while to ensure if we have sufficient difference between breakpoints.
        model_sparsity = max(float(1/self._max_num_of_bkpts), self._espilon)
        sparse_bkpt = unique_list(sparse_enough_breakpoints(symmetrized_bkpts, model_sparsity))
        if frac_f not in sparse_bkpt:
            sparse_bkpt.append(frac_f)
        num_bkpt = len(sparse_bkpt)
        if num_bkpt == 2:
            cut_generation_problem_logger.debug("Parsed row data suggests to use GMIC.")
            cut_generation_problem_logger.debug("Dim of value polyhedron: 0")
            pi_p =  gmic(frac_f)
            log_problem_result(sparse_bkpt, [0, 1], binvarow, binvc, f)
            if self._prove_seperator:
                # we always have a separator here.
                cut_generation_problem_logger.debug(f"The minimality of the found cgf is {True}")
            # return gmic, the feasible set for the optimization problem is a single point which corresponds to gmic.
            return pi_p
        # ensure a breakpoint sequence is given
        sparse_bkpt.sort()
        sparse_bkpt = [QQ(bi) for bi in sparse_bkpt]
        f_index = sparse_bkpt.index(frac_f)
        self._cut_score.set_f_index(f_index)
        value_polyhedron = value_nnc_polyhedron_value_cords(sparse_bkpt, f_index, backend=self._backend)
        cut_generation_problem_logger.debug(f"Dim of value polyhedron : {value_polyhedron.upstairs().ambient_dim()}")
        linear_constraints, x =  self._solver.write_linear_constraints_from_bsa(value_polyhedron)
        if self._cut_score._cut_score.is_linear():
            objective = self._cut_score._cut_score.wrap_cut_score_to_solver_linear_objective(self._solver, mip_obj=binvc, x=x, bkpt=sparse_bkpt, f_index=f_index, objective_sense=self._objective_sense)
        else:
            raise ValueError("This method only works for linear objective functions. Try using the bkpt_as_param algorithm.")
        obj_val, values, status, prob_res = self._solver.lp_solve(linear_constraints, objective, x=x)
        cut_generation_problem_logger.debug(f"status: {status}, obj_val: {obj_val}")
        values = [QQ(v) for v in values]
        point = sparse_bkpt+values
        self._cut_score.set_current_cell(value_polyhedron)
        try:
            b, v = self._cut_score.validate_point(point)
        except ModelViolation:
            b = sparse_bkpt
            v = values
        pi_p = piecewise_function_from_breakpoints_and_values(b+[1], v+[0])
        log_problem_result(b, v, binvarow, binvc, f)
        if self._prove_seperator:
            res = minimality_test(pi_p, self._show_proof) # add someway to log certificates.
            cut_generation_problem_logger.info(f"Minimality of cgf: {res}")
        return pi_p


    def _algorithm_custom(self, binvarow, binvc, f):
        # For future use.
        raise NotImplementedError

    
    def get_cgp_input_parameters(self):
        """
        Returns a dictionary parameters used to initalize the cut generation problem.
        """
        return self._cgp_input_parameters
